app = "repowork"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_PUBLIC_YOUTUBE_API_KEY = "AIzaSyCox-p0kSRp1-J0UpAFJKjYQ24SDZ9jR9I"
  NEXT_PUBLIC_APP_URL = "https://repowork.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0